+ALTER TABLE maps
ADD COLUMN grid_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN grid_cols INT DEFAULT 10,
ADD COLUMN grid_rows INT DEFAULT 10,
ADD COLUMN grid_color VARCHAR(20) DEFAULT 'white',
ADD COLUMN grid_opacity INT DEFAULT 100;


